### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by fengfangqian** [vilic/cordova-plugin-wechat#8]
fengfangqiandeMacBook-Pro:xqb-app fengfangqian$ cordova plugin add com.wordsbaking.cordova.wechat --variable APP_ID=wxb72feca57491164c
Fetching plugin "com.wordsbaking.cordova.wechat" via plugin registry
npm http GET http://registry.cordova.io/com.wordsbaking.cordova.wechat
npm http 304 http://registry.cordova.io/com.wordsbaking.cordova.wechat
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.wordsbaking.cordova.wechat/-/com.wordsbaking.cordova.wechat-0.3.0.tgz
npm http 200 http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.wordsbaking.cordova.wechat/-/com.wordsbaking.cordova.wechat-0.3.0.tgz
Installing "com.wordsbaking.cordova.wechat" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.wordsbaking.cordova.wechat':Error: Uh oh!
"/Users/fengfangqian/www/xiaoqianbao/client/trunk/xqb-app/platforms/android/libs/libammsdk.jar" already exists!
    at Object.module.exports.common.copyNewFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
    at module.exports.source-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:67:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:575:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
Error: Uh oh!
"/Users/fengfangqian/www/xiaoqianbao/client/trunk/xqb-app/platforms/android/libs/libammsdk.jar" already exists!
    at Object.module.exports.common.copyNewFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
    at module.exports.source-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:67:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:575:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by fengfangqian** [comment]
cordova plugin add https://github.com/vilic/cordova-plugin-wechat.git --variable APP_ID=wxb72feca57491164c
这样ok

**Comment by vilic** [comment]
囧, 看报错貌似是已经存在相关 jar 文件的原因.

**Comment by fengfangqian** [comment]
我重新删除再安装已经ok了，但是现在拉不起微信，微信闪退看到这个错误日志
04-23 01:01:08.024: D/CordovaLog(26082): file:///android_asset/www/invitation-on.html: Line 40 : ERR_AUTH_DENIED
04-23 01:01:08.024: I/chromium(26082): [INFO:CONSOLE(40)] "ERR_AUTH_DENIED", source: file:///android_asset/www/invitation-on.html (40)

**Comment by vilic** [comment]
https://github.com/vilic/cordova-plugin-wechat/issues/6#issuecomment-78209971

**Comment by fengfangqian** [comment]
想问下,支持分享到朋友圈么?

**Comment by vilic** [comment]
支持的~

Sent from my Lumia 930
________________________________

**Comment by fengfangqian** [comment]
@vilic 报这个错是什么导致的
function sharewechat(){
            alert("微信");
            WeChat.share('文本', WeChat.Scene.session, function () {
                alert('分享成功~');
                //console.log('分享成功~');
            }, function (reason) {
                alert("分享失败");
                //console.log(reason);
            });

        }    

04-23 16:57:20.269: I/chromium(27551): [INFO:CONSOLE(35)] "Uncaught ReferenceError: WeChat is not defined", source: file:///android_asset/www/invitation-on.html (35)

**Comment by fengfangqian** [comment]
@vilic  04-23 18:32:07.634: I/chromium(3091): [INFO:CONSOLE(50)] "ERR_AUTH_DENIED", source: file:///android_asset/www/invitation-on.html (50)
这是啥问题

**Comment by vilic** [comment]
如果微信打开了, 那就不关这边什么事了. 有时候是缓存问题, 具体微信那边文档也没说清楚的.

**Comment by fengfangqian** [comment]
@vilic 你好，在nexus5上分享可以正常使用，但是换个手机就出现分享受限，hit push hold!无法分享到微信，能帮忙分析下原因么

**Comment by vilic** [comment]
你好，没遇到过这个情况，会不会是appid使用超限了？

Sent from my Lumia 930
________________________________

**Comment by fengfangqian** [comment]
@vilic 再使用的时候又好了，不知道啥问题，再观察下，谢谢

**Comment by vilic** [comment]
:)
